scriptencoding utf-8

" set packpath+=$VIM_CONFIG_PATH
set nocompatible " 关闭vi兼容模式
set noswapfile " 关闭.swp文件
set t_Co=256 " 开启终端256色 terminal Color
set showcmd
set foldenable
set foldmethod=manual
set cc=100
"set foldmethod=marker
set autoindent
set cindent
set equalalways "分隔窗口始终平分
"set mouse=a
"set background=light
colorscheme desert
"colorscheme peachpuff
"colo peachpuff
"set termguicolors
set laststatus=2 " 总是显示状态栏
set ruler " 显示光标当前位置
set number " 开启行号显示
set colorcolumn=100 " 竖线标记，限制代码行宽
set cursorline " 高亮显示当前行/列
set cursorcolumn
set showmode
set hlsearch " 高亮显示搜索结果
set incsearch
set magic
set showmatch
set binary
set noeol
set lcs=tab:▸\ ,trail:·,eol:¬,nbsp:_
set list
set ttyfast
set so=1
syntax enable " 开启语法高亮功能
"syntax on " 允许用指定语法高亮配色方案替换默认方案 自适应不同语言的智能缩进
filetype on
filetype plugin on
filetype indent on
set autoread
set expandtab " 将制表符扩展为空格
set tabstop=4 " 设置编辑时制表符占用空格数
set shiftwidth=4 " 设置格式化时制表符占用空格数
set softtabstop=4 " 让 vim 把连续数量的空格视为一个制表符
" set splitbelow " Open new windows below the current window.
set splitright
" color
" color dracula
set showmatch "  括号成对匹配 简写为set sm
set modifiable
set wildmenu " 增加命令行自动补全操作
set history=9999

" set hidden
let g:racer_cmd = '/Users/yakir/local/rust/bin/racer'
let g:racer_experimental_completer = 1
let g:rustfmt_autosave = 1
let g:rust_clip_command = 'pbcopy'
let g:go_version_warning = 0

" color
let g:cpatch_path = '~/.vim/colors/patch'

"let g:terminal_ansi_colors

" Plugin indentLine settings.
let g:indentLine_char = "┆"
let g:indentLine_enabled = 1
let g:autopep8_disable_show_diff = 1
let g:NERDTreeShowIgnoredStatus = 1
let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "✹",
    \ "Staged"    : "✚",
    \ "Untracked" : "✭",
    \ "Renamed"   : "➜",
    \ "Unmerged"  : "═",
    \ "Deleted"   : "✖",
    \ "Dirty"     : "✗",
    \ "Clean"     : "✔︎",
    \ "Unknown"   : "?"
    \ }
"\ 'Ignored'   : '☒',


highlight CursorColumn ctermbg=235 guibg=#555555
highlight CursorLine ctermbg=235 guibg=#555555

source /Users/yakir/Library/Mobile Documents/com~apple~CloudDocs/Developer/macOS-libs/vim/plugins.vim
source /Users/yakir/Library/Mobile Documents/com~apple~CloudDocs/Developer/macOS-libs/vim/mappings.vim
