live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x928374"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xebdbb2"
yellow = "0xfabd2f"

[colors.normal]
black = "0x282828"
blue = "0x458588"
cyan = "0x689d6a"
green = "0x98971a"
magenta = "0xb16286"
red = "0xcc241d"
white = "0xa89984"
yellow = "0xd79921"

[colors.primary]
background = "0x282828"
foreground = "0xebdbb2"

[cursor.style]
shape = "Underline"

[font]
size = 11.0

[[keyboard.bindings]]
chars = "\u001Cc"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C&"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Cx"
key = "X"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Ct"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C%"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C\""
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001CM"
key = "L"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001Cp"
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001Cn"
key = "RBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001C["
key = "C"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001C1"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C2"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C3"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C4"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C5"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C6"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C7"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C8"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C9"
key = "Key9"
mods = "Command"

[scrolling]
history = 100000

[shell]
args = ["--login", "-c", "/Users/yakir/local/brew/bin/tmux new-session -A -D -s ' 🌵 '"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
decorations_theme_variant = "None"

[window.class]
instance = "Alacritty"

[window.dimensions]
columns = 150
lines = 86

[window.padding]
x = 1
y = 1
