live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.footer_bar]
background = "#ebdbb2"
foreground = "#282828"

[colors.hints.end]
background = "#FF003C"
foreground = "#F8B8B8"

[colors.hints.start]
background = "#F8B8B8"
foreground = "#FF003C"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors.search.focused_match]
background = "#FF003C"
foreground = "#ebdbb2"

[colors.search.matches]
background = "#F8B8B8"
foreground = "#FF003C"

[cursor.style]
shape = "Underline"

[font]
size = 11

[[keyboard.bindings]]
chars = "\u001Cc"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C&"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Cx"
key = "X"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Ct"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C%"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C\""
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001Cz"
key = "F"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Co"
key = "S"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001CM"
key = "L"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001Cp"
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001Cn"
key = "RBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001C["
key = "C"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001C1"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C2"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C3"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C4"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C5"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C6"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C7"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C8"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C9"
key = "Key9"
mods = "Command"

[scrolling]
history = 100000
multiplier = 2

[shell]
args = ["--login", "-c", "/Users/yakir/local/brew/bin/tmux new-session -A -D -s ' '"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
decorations_theme_variant = "None"

[window.class]
instance = "Alacritty"

[window.dimensions]
columns = 150
lines = 86

[window.padding]
x = 1
y = 1
